version: '3.7'

services:

#
# letsencrypt
# This container sets up an Nginx webserver and reverse proxy with php support 
# and a built-in letsencrypt client that automates free SSL server certificate generation and renewal processes. 
# It also contains fail2ban for intrusion prevention.
#
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    privileged: true
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PGID=1000
      - PUID=1000
      - EMAIL=${EMAIL}
      - URL=${URL}
      - EXTRA_DOMAINS=${EXTRA_DOMAINS}
      - DHLEVEL=2048
      - TZ=${TZ}
      - VALIDATION=http
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/centos/letsencrypt:/config
      - /home/centos/lightsail-htpc/nginx:/config/nginx/site-confs/default
    depends_on:
      - "no-ip"
      - "plex"
    extra_hosts:
      - "plex:${HOST_IP}"
    networks:
      - app_net
    healthcheck:
     test: ["CMD-SHELL", "curl -f --insecure https://localhost && echo 'OK'"]
     interval: 5s
     timeout: 2s
     retries: 20

#
# no-ip
# This is a simple Docker container for running the No-IP2 dynamic DNS update script. 
# It will keep your domain.ddns.net DNS alias up-to-date as your home IP changes.
#
  no-ip:
    image: coppit/no-ip
    container_name: noip
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/centos/noip:/config
      - /home/centos/lightsail-htpc/noip.conf:/config/noip.conf
    environment:
      - PGID=1000 #optional
      - PUID=1000 #optional
      
#
# plex
# Plex organizes video, music and photos from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices.
# This container is packaged as a standalone Plex Media Server.
#
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: "host"
    restart: always
    volumes:
      - /home/centos/plex:/config
      - /home/centos/tv:/data/tvshows
      - /home/centos/movies:/data/movies
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=${TZ}
      - VERSION=docker
    healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost:32400/web && echo 'OK'"]
     interval: 5s
     timeout: 2s
     retries: 20

#
# network
#
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 172.20.0.0/16
